// Localized *display* labels for the interest taxonomy in lib/interests.ts.
//
// The raw Turkish strings in INTEREST_CATEGORIES (e.g. "🎵 Müzik") are the actual stored/matched
// values on `users.interests` (see the header comment in interests.ts) — that stored format does
// NOT change here, only what's rendered. Every raw interest string is a lookup key into this
// locale table (emoji prefixes stay identical across locales, matching the convention already
// used for RELATIONSHIP_GOAL/ZODIAC labels in profileLabels.ts); a key with no entry in a given
// locale falls back to the raw (Turkish) string via getLocalizedInterestLabel's own fallback.
import type { AppLocale } from '../i18n/appLocale';
import { localeLookup } from './profileLabels';

type LocaleTable = Record<AppLocale, Record<string, string>>;

export const INTEREST_CATEGORY_TITLES_BY_LOCALE: LocaleTable = {
  tr: {
    music: 'Müzik & Gece Hayatı', culture: 'Sinema & Kültür', travel: 'Seyahat & Doğa',
    food: 'Yeme & İçme', sport: 'Spor & Wellness', creative: 'Yaratıcılık & Teknoloji',
    social: 'Sosyal & Yaşam Tarzı',
  },
  en: {
    music: 'Music & Nightlife', culture: 'Cinema & Culture', travel: 'Travel & Nature',
    food: 'Food & Drink', sport: 'Sports & Wellness', creative: 'Creativity & Technology',
    social: 'Social & Lifestyle',
  },
  es: {
    music: 'Música y Vida Nocturna', culture: 'Cine y Cultura', travel: 'Viajes y Naturaleza',
    food: 'Comida y Bebida', sport: 'Deporte y Bienestar', creative: 'Creatividad y Tecnología',
    social: 'Social y Estilo de Vida',
  },
  fr: {
    music: 'Musique & Vie Nocturne', culture: 'Cinéma & Culture', travel: 'Voyage & Nature',
    food: 'Gastronomie & Boissons', sport: 'Sport & Bien-être', creative: 'Créativité & Technologie',
    social: 'Social & Style de Vie',
  },
  pt: {
    music: 'Música e Vida Noturna', culture: 'Cinema e Cultura', travel: 'Viagem e Natureza',
    food: 'Comida e Bebida', sport: 'Esporte e Bem-estar', creative: 'Criatividade e Tecnologia',
    social: 'Social e Estilo de Vida',
  },
  ru: {
    music: 'Музыка и Ночная Жизнь', culture: 'Кино и Культура', travel: 'Путешествия и Природа',
    food: 'Еда и Напитки', sport: 'Спорт и Велнес', creative: 'Творчество и Технологии',
    social: 'Общение и Стиль Жизни',
  },
  ar: {
    music: 'الموسيقى والحياة الليلية', culture: 'السينما والثقافة', travel: 'السفر والطبيعة',
    food: 'الطعام والشراب', sport: 'الرياضة والعافية', creative: 'الإبداع والتقنية',
    social: 'الحياة الاجتماعية ونمط الحياة',
  },
  hi: {
    music: 'संगीत और नाइटलाइफ़', culture: 'सिनेमा और संस्कृति', travel: 'यात्रा और प्रकृति',
    food: 'खाना-पीना', sport: 'खेल और वेलनेस', creative: 'रचनात्मकता और तकनीक',
    social: 'सामाजिक और जीवनशैली',
  },
  zh: {
    music: '音乐与夜生活', culture: '电影与文化', travel: '旅行与自然',
    food: '美食与饮品', sport: '运动与健康', creative: '创意与科技',
    social: '社交与生活方式',
  },
};

export const INTEREST_LABELS_BY_LOCALE: LocaleTable = {
  tr: {
    '🎵 Müzik': '🎵 Müzik', '🎧 Elektronik Müzik': '🎧 Elektronik Müzik', '🎛️ Techno': '🎛️ Techno',
    '🪩 Rave / Club': '🪩 Rave / Club', '🎤 Konser': '🎤 Konser', '🎸 Rock': '🎸 Rock',
    '🎹 Indie': '🎹 Indie', '🎙️ Hip-Hop': '🎙️ Hip-Hop', '🎶 Pop': '🎶 Pop', '🎷 Jazz': '🎷 Jazz',
    '🎼 Klasik': '🎼 Klasik', '🕺 Gece Hayatı': '🕺 Gece Hayatı', '🍸 Kokteyl Mekanları': '🍸 Kokteyl Mekanları',
    '🎉 Festival': '🎉 Festival',
    '🎬 Sinema': '🎬 Sinema', '📺 Diziler': '📺 Diziler', '🎭 Tiyatro': '🎭 Tiyatro', '🎨 Sanat': '🎨 Sanat',
    '🏛️ Müze': '🏛️ Müze', '📚 Kitap': '📚 Kitap', '✍️ Yazarlık': '✍️ Yazarlık', '📖 Şiir': '📖 Şiir',
    '🎞️ Bağımsız Filmler': '🎞️ Bağımsız Filmler', '😂 Komedi': '😂 Komedi', '🎌 Anime': '🎌 Anime',
    '✈️ Seyahat': '✈️ Seyahat', '🏕️ Kamp': '🏕️ Kamp', '🥾 Hiking': '🥾 Hiking', '🏖️ Sahil': '🏖️ Sahil',
    '🌿 Doğa': '🌿 Doğa', '🚗 Road Trip': '🚗 Road Trip', '🏔️ Dağlar': '🏔️ Dağlar',
    '🌍 Yeni Kültürler': '🌍 Yeni Kültürler', '🧳 Weekend Getaway': '🧳 Weekend Getaway', '🌅 Gün Batımı': '🌅 Gün Batımı',
    '☕ Kahve': '☕ Kahve', '🍕 Pizza': '🍕 Pizza', '🍣 Sushi': '🍣 Sushi', '🍝 İtalyan Mutfağı': '🍝 İtalyan Mutfağı',
    '🌮 Sokak Lezzetleri': '🌮 Sokak Lezzetleri', '🍳 Brunch': '🍳 Brunch', '🍰 Tatlı': '🍰 Tatlı',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Yemek Yapmak', '🍵 Çay': '🍵 Çay', '🥗 Sağlıklı Beslenme': '🥗 Sağlıklı Beslenme',
    '🏋️ Fitness': '🏋️ Fitness', '🏃 Koşu': '🏃 Koşu', '⚽ Futbol': '⚽ Futbol', '🏀 Basketbol': '🏀 Basketbol',
    '🎾 Tenis': '🎾 Tenis', '🏊 Yüzme': '🏊 Yüzme', '🚴 Bisiklet': '🚴 Bisiklet', '🧘 Yoga': '🧘 Yoga',
    '🥊 Boks': '🥊 Boks', '🏄 Su Sporları': '🏄 Su Sporları', '🎿 Kayak': '🎿 Kayak', '💪 Gym': '💪 Gym',
    '📷 Fotoğrafçılık': '📷 Fotoğrafçılık', '🎥 Video': '🎥 Video', '🎨 Tasarım': '🎨 Tasarım',
    '💻 Teknoloji': '💻 Teknoloji', '🤖 Yapay Zeka': '🤖 Yapay Zeka', '🎮 Oyun': '🎮 Oyun',
    '🕹️ Retro Oyun': '🕹️ Retro Oyun', '🎧 Podcast': '🎧 Podcast', '🎹 Müzik Üretimi': '🎹 Müzik Üretimi',
    '🧑‍💻 Kodlama': '🧑‍💻 Kodlama',
    '🐾 Evcil Hayvanlar': '🐾 Evcil Hayvanlar', '🐶 Köpekler': '🐶 Köpekler', '🐱 Kediler': '🐱 Kediler',
    '💃 Dans': '💃 Dans', '🪩 Clubbing': '🪩 Clubbing', '🎉 Partiler': '🎉 Partiler',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Arkadaşlarla Takılmak',
    '🧠 Kişisel Gelişim': '🧠 Kişisel Gelişim', '♟️ Masa Oyunları': '♟️ Masa Oyunları', '🎲 Board Games': '🎲 Board Games',
    '🚘 Arabalar': '🚘 Arabalar', '🏍️ Motosiklet': '🏍️ Motosiklet',
  },
  en: {
    '🎵 Müzik': '🎵 Music', '🎧 Elektronik Müzik': '🎧 Electronic Music', '🎛️ Techno': '🎛️ Techno',
    '🪩 Rave / Club': '🪩 Rave / Club', '🎤 Konser': '🎤 Concerts', '🎸 Rock': '🎸 Rock',
    '🎹 Indie': '🎹 Indie', '🎙️ Hip-Hop': '🎙️ Hip-Hop', '🎶 Pop': '🎶 Pop', '🎷 Jazz': '🎷 Jazz',
    '🎼 Klasik': '🎼 Classical', '🕺 Gece Hayatı': '🕺 Nightlife', '🍸 Kokteyl Mekanları': '🍸 Cocktail Bars',
    '🎉 Festival': '🎉 Festivals',
    '🎬 Sinema': '🎬 Movies', '📺 Diziler': '📺 TV Shows', '🎭 Tiyatro': '🎭 Theatre', '🎨 Sanat': '🎨 Art',
    '🏛️ Müze': '🏛️ Museums', '📚 Kitap': '📚 Books', '✍️ Yazarlık': '✍️ Writing', '📖 Şiir': '📖 Poetry',
    '🎞️ Bağımsız Filmler': '🎞️ Indie Films', '😂 Komedi': '😂 Comedy', '🎌 Anime': '🎌 Anime',
    '✈️ Seyahat': '✈️ Travel', '🏕️ Kamp': '🏕️ Camping', '🥾 Hiking': '🥾 Hiking', '🏖️ Sahil': '🏖️ Beach',
    '🌿 Doğa': '🌿 Nature', '🚗 Road Trip': '🚗 Road Trips', '🏔️ Dağlar': '🏔️ Mountains',
    '🌍 Yeni Kültürler': '🌍 New Cultures', '🧳 Weekend Getaway': '🧳 Weekend Getaways', '🌅 Gün Batımı': '🌅 Sunsets',
    '☕ Kahve': '☕ Coffee', '🍕 Pizza': '🍕 Pizza', '🍣 Sushi': '🍣 Sushi', '🍝 İtalyan Mutfağı': '🍝 Italian Food',
    '🌮 Sokak Lezzetleri': '🌮 Street Food', '🍳 Brunch': '🍳 Brunch', '🍰 Tatlı': '🍰 Desserts',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Cooking', '🍵 Çay': '🍵 Tea', '🥗 Sağlıklı Beslenme': '🥗 Healthy Eating',
    '🏋️ Fitness': '🏋️ Fitness', '🏃 Koşu': '🏃 Running', '⚽ Futbol': '⚽ Football', '🏀 Basketbol': '🏀 Basketball',
    '🎾 Tenis': '🎾 Tennis', '🏊 Yüzme': '🏊 Swimming', '🚴 Bisiklet': '🚴 Cycling', '🧘 Yoga': '🧘 Yoga',
    '🥊 Boks': '🥊 Boxing', '🏄 Su Sporları': '🏄 Water Sports', '🎿 Kayak': '🎿 Skiing', '💪 Gym': '💪 Gym',
    '📷 Fotoğrafçılık': '📷 Photography', '🎥 Video': '🎥 Video', '🎨 Tasarım': '🎨 Design',
    '💻 Teknoloji': '💻 Technology', '🤖 Yapay Zeka': '🤖 Artificial Intelligence', '🎮 Oyun': '🎮 Gaming',
    '🕹️ Retro Oyun': '🕹️ Retro Gaming', '🎧 Podcast': '🎧 Podcasts', '🎹 Müzik Üretimi': '🎹 Music Production',
    '🧑‍💻 Kodlama': '🧑‍💻 Coding',
    '🐾 Evcil Hayvanlar': '🐾 Pets', '🐶 Köpekler': '🐶 Dogs', '🐱 Kediler': '🐱 Cats',
    '💃 Dans': '💃 Dance', '🪩 Clubbing': '🪩 Clubbing', '🎉 Partiler': '🎉 Parties',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Hanging Out with Friends',
    '🧠 Kişisel Gelişim': '🧠 Personal Growth', '♟️ Masa Oyunları': '♟️ Tabletop Games', '🎲 Board Games': '🎲 Board Games',
    '🚘 Arabalar': '🚘 Cars', '🏍️ Motosiklet': '🏍️ Motorcycles',
  },
  es: {
    '🎵 Müzik': '🎵 Música', '🎧 Elektronik Müzik': '🎧 Música Electrónica', '🎛️ Techno': '🎛️ Techno',
    '🪩 Rave / Club': '🪩 Rave / Club', '🎤 Konser': '🎤 Conciertos', '🎸 Rock': '🎸 Rock',
    '🎹 Indie': '🎹 Indie', '🎙️ Hip-Hop': '🎙️ Hip-Hop', '🎶 Pop': '🎶 Pop', '🎷 Jazz': '🎷 Jazz',
    '🎼 Klasik': '🎼 Clásica', '🕺 Gece Hayatı': '🕺 Vida Nocturna', '🍸 Kokteyl Mekanları': '🍸 Bares de Cócteles',
    '🎉 Festival': '🎉 Festivales',
    '🎬 Sinema': '🎬 Cine', '📺 Diziler': '📺 Series', '🎭 Tiyatro': '🎭 Teatro', '🎨 Sanat': '🎨 Arte',
    '🏛️ Müze': '🏛️ Museos', '📚 Kitap': '📚 Libros', '✍️ Yazarlık': '✍️ Escritura', '📖 Şiir': '📖 Poesía',
    '🎞️ Bağımsız Filmler': '🎞️ Cine Independiente', '😂 Komedi': '😂 Comedia', '🎌 Anime': '🎌 Anime',
    '✈️ Seyahat': '✈️ Viajar', '🏕️ Kamp': '🏕️ Camping', '🥾 Hiking': '🥾 Senderismo', '🏖️ Sahil': '🏖️ Playa',
    '🌿 Doğa': '🌿 Naturaleza', '🚗 Road Trip': '🚗 Viaje por Carretera', '🏔️ Dağlar': '🏔️ Montañas',
    '🌍 Yeni Kültürler': '🌍 Nuevas Culturas', '🧳 Weekend Getaway': '🧳 Escapada de Fin de Semana', '🌅 Gün Batımı': '🌅 Atardeceres',
    '☕ Kahve': '☕ Café', '🍕 Pizza': '🍕 Pizza', '🍣 Sushi': '🍣 Sushi', '🍝 İtalyan Mutfağı': '🍝 Comida Italiana',
    '🌮 Sokak Lezzetleri': '🌮 Comida Callejera', '🍳 Brunch': '🍳 Brunch', '🍰 Tatlı': '🍰 Postres',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Cocinar', '🍵 Çay': '🍵 Té', '🥗 Sağlıklı Beslenme': '🥗 Alimentación Saludable',
    '🏋️ Fitness': '🏋️ Fitness', '🏃 Koşu': '🏃 Correr', '⚽ Futbol': '⚽ Fútbol', '🏀 Basketbol': '🏀 Baloncesto',
    '🎾 Tenis': '🎾 Tenis', '🏊 Yüzme': '🏊 Natación', '🚴 Bisiklet': '🚴 Ciclismo', '🧘 Yoga': '🧘 Yoga',
    '🥊 Boks': '🥊 Boxeo', '🏄 Su Sporları': '🏄 Deportes Acuáticos', '🎿 Kayak': '🎿 Esquí', '💪 Gym': '💪 Gimnasio',
    '📷 Fotoğrafçılık': '📷 Fotografía', '🎥 Video': '🎥 Video', '🎨 Tasarım': '🎨 Diseño',
    '💻 Teknoloji': '💻 Tecnología', '🤖 Yapay Zeka': '🤖 Inteligencia Artificial', '🎮 Oyun': '🎮 Videojuegos',
    '🕹️ Retro Oyun': '🕹️ Juegos Retro', '🎧 Podcast': '🎧 Podcasts', '🎹 Müzik Üretimi': '🎹 Producción Musical',
    '🧑‍💻 Kodlama': '🧑‍💻 Programación',
    '🐾 Evcil Hayvanlar': '🐾 Mascotas', '🐶 Köpekler': '🐶 Perros', '🐱 Kediler': '🐱 Gatos',
    '💃 Dans': '💃 Bailar', '🪩 Clubbing': '🪩 Discotecas', '🎉 Partiler': '🎉 Fiestas',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Salir con Amigos',
    '🧠 Kişisel Gelişim': '🧠 Desarrollo Personal', '♟️ Masa Oyunları': '♟️ Juegos de Mesa', '🎲 Board Games': '🎲 Juegos de Mesa',
    '🚘 Arabalar': '🚘 Coches', '🏍️ Motosiklet': '🏍️ Motocicletas',
  },
  fr: {
    '🎵 Müzik': '🎵 Musique', '🎧 Elektronik Müzik': '🎧 Musique Électronique', '🎛️ Techno': '🎛️ Techno',
    '🪩 Rave / Club': '🪩 Rave / Club', '🎤 Konser': '🎤 Concerts', '🎸 Rock': '🎸 Rock',
    '🎹 Indie': '🎹 Indie', '🎙️ Hip-Hop': '🎙️ Hip-Hop', '🎶 Pop': '🎶 Pop', '🎷 Jazz': '🎷 Jazz',
    '🎼 Klasik': '🎼 Classique', '🕺 Gece Hayatı': '🕺 Vie Nocturne', '🍸 Kokteyl Mekanları': '🍸 Bars à Cocktails',
    '🎉 Festival': '🎉 Festivals',
    '🎬 Sinema': '🎬 Cinéma', '📺 Diziler': '📺 Séries', '🎭 Tiyatro': '🎭 Théâtre', '🎨 Sanat': '🎨 Art',
    '🏛️ Müze': '🏛️ Musées', '📚 Kitap': '📚 Livres', '✍️ Yazarlık': '✍️ Écriture', '📖 Şiir': '📖 Poésie',
    '🎞️ Bağımsız Filmler': '🎞️ Films Indépendants', '😂 Komedi': '😂 Comédie', '🎌 Anime': '🎌 Anime',
    '✈️ Seyahat': '✈️ Voyage', '🏕️ Kamp': '🏕️ Camping', '🥾 Hiking': '🥾 Randonnée', '🏖️ Sahil': '🏖️ Plage',
    '🌿 Doğa': '🌿 Nature', '🚗 Road Trip': '🚗 Road Trip', '🏔️ Dağlar': '🏔️ Montagnes',
    '🌍 Yeni Kültürler': '🌍 Nouvelles Cultures', '🧳 Weekend Getaway': '🧳 Escapade de Weekend', '🌅 Gün Batımı': '🌅 Couchers de Soleil',
    '☕ Kahve': '☕ Café', '🍕 Pizza': '🍕 Pizza', '🍣 Sushi': '🍣 Sushi', '🍝 İtalyan Mutfağı': '🍝 Cuisine Italienne',
    '🌮 Sokak Lezzetleri': '🌮 Street Food', '🍳 Brunch': '🍳 Brunch', '🍰 Tatlı': '🍰 Desserts',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Cuisiner', '🍵 Çay': '🍵 Thé', '🥗 Sağlıklı Beslenme': '🥗 Alimentation Saine',
    '🏋️ Fitness': '🏋️ Fitness', '🏃 Koşu': '🏃 Course à Pied', '⚽ Futbol': '⚽ Football', '🏀 Basketbol': '🏀 Basketball',
    '🎾 Tenis': '🎾 Tennis', '🏊 Yüzme': '🏊 Natation', '🚴 Bisiklet': '🚴 Vélo', '🧘 Yoga': '🧘 Yoga',
    '🥊 Boks': '🥊 Boxe', '🏄 Su Sporları': '🏄 Sports Nautiques', '🎿 Kayak': '🎿 Ski', '💪 Gym': '💪 Salle de Sport',
    '📷 Fotoğrafçılık': '📷 Photographie', '🎥 Video': '🎥 Vidéo', '🎨 Tasarım': '🎨 Design',
    '💻 Teknoloji': '💻 Technologie', '🤖 Yapay Zeka': '🤖 Intelligence Artificielle', '🎮 Oyun': '🎮 Jeux Vidéo',
    '🕹️ Retro Oyun': '🕹️ Jeux Rétro', '🎧 Podcast': '🎧 Podcasts', '🎹 Müzik Üretimi': '🎹 Production Musicale',
    '🧑‍💻 Kodlama': '🧑‍💻 Programmation',
    '🐾 Evcil Hayvanlar': '🐾 Animaux de Compagnie', '🐶 Köpekler': '🐶 Chiens', '🐱 Kediler': '🐱 Chats',
    '💃 Dans': '💃 Danse', '🪩 Clubbing': '🪩 Clubbing', '🎉 Partiler': '🎉 Fêtes',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Sorties Entre Amis',
    '🧠 Kişisel Gelişim': '🧠 Développement Personnel', '♟️ Masa Oyunları': '♟️ Jeux de Société', '🎲 Board Games': '🎲 Board Games',
    '🚘 Arabalar': '🚘 Voitures', '🏍️ Motosiklet': '🏍️ Motos',
  },
  pt: {
    '🎵 Müzik': '🎵 Música', '🎧 Elektronik Müzik': '🎧 Música Eletrônica', '🎛️ Techno': '🎛️ Techno',
    '🪩 Rave / Club': '🪩 Rave / Balada', '🎤 Konser': '🎤 Shows', '🎸 Rock': '🎸 Rock',
    '🎹 Indie': '🎹 Indie', '🎙️ Hip-Hop': '🎙️ Hip-Hop', '🎶 Pop': '🎶 Pop', '🎷 Jazz': '🎷 Jazz',
    '🎼 Klasik': '🎼 Clássica', '🕺 Gece Hayatı': '🕺 Vida Noturna', '🍸 Kokteyl Mekanları': '🍸 Bares de Coquetéis',
    '🎉 Festival': '🎉 Festivais',
    '🎬 Sinema': '🎬 Cinema', '📺 Diziler': '📺 Séries', '🎭 Tiyatro': '🎭 Teatro', '🎨 Sanat': '🎨 Arte',
    '🏛️ Müze': '🏛️ Museus', '📚 Kitap': '📚 Livros', '✍️ Yazarlık': '✍️ Escrita', '📖 Şiir': '📖 Poesia',
    '🎞️ Bağımsız Filmler': '🎞️ Filmes Independentes', '😂 Komedi': '😂 Comédia', '🎌 Anime': '🎌 Anime',
    '✈️ Seyahat': '✈️ Viagem', '🏕️ Kamp': '🏕️ Acampamento', '🥾 Hiking': '🥾 Trilhas', '🏖️ Sahil': '🏖️ Praia',
    '🌿 Doğa': '🌿 Natureza', '🚗 Road Trip': '🚗 Viagem de Carro', '🏔️ Dağlar': '🏔️ Montanhas',
    '🌍 Yeni Kültürler': '🌍 Novas Culturas', '🧳 Weekend Getaway': '🧳 Escapada de Fim de Semana', '🌅 Gün Batımı': '🌅 Pôr do Sol',
    '☕ Kahve': '☕ Café', '🍕 Pizza': '🍕 Pizza', '🍣 Sushi': '🍣 Sushi', '🍝 İtalyan Mutfağı': '🍝 Comida Italiana',
    '🌮 Sokak Lezzetleri': '🌮 Comida de Rua', '🍳 Brunch': '🍳 Brunch', '🍰 Tatlı': '🍰 Sobremesas',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Cozinhar', '🍵 Çay': '🍵 Chá', '🥗 Sağlıklı Beslenme': '🥗 Alimentação Saudável',
    '🏋️ Fitness': '🏋️ Fitness', '🏃 Koşu': '🏃 Corrida', '⚽ Futbol': '⚽ Futebol', '🏀 Basketbol': '🏀 Basquete',
    '🎾 Tenis': '🎾 Tênis', '🏊 Yüzme': '🏊 Natação', '🚴 Bisiklet': '🚴 Ciclismo', '🧘 Yoga': '🧘 Yoga',
    '🥊 Boks': '🥊 Boxe', '🏄 Su Sporları': '🏄 Esportes Aquáticos', '🎿 Kayak': '🎿 Esqui', '💪 Gym': '💪 Academia',
    '📷 Fotoğrafçılık': '📷 Fotografia', '🎥 Video': '🎥 Vídeo', '🎨 Tasarım': '🎨 Design',
    '💻 Teknoloji': '💻 Tecnologia', '🤖 Yapay Zeka': '🤖 Inteligência Artificial', '🎮 Oyun': '🎮 Games',
    '🕹️ Retro Oyun': '🕹️ Jogos Retrô', '🎧 Podcast': '🎧 Podcasts', '🎹 Müzik Üretimi': '🎹 Produção Musical',
    '🧑‍💻 Kodlama': '🧑‍💻 Programação',
    '🐾 Evcil Hayvanlar': '🐾 Animais de Estimação', '🐶 Köpekler': '🐶 Cachorros', '🐱 Kediler': '🐱 Gatos',
    '💃 Dans': '💃 Dança', '🪩 Clubbing': '🪩 Balada', '🎉 Partiler': '🎉 Festas',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Sair com Amigos',
    '🧠 Kişisel Gelişim': '🧠 Desenvolvimento Pessoal', '♟️ Masa Oyunları': '♟️ Jogos de Tabuleiro', '🎲 Board Games': '🎲 Board Games',
    '🚘 Arabalar': '🚘 Carros', '🏍️ Motosiklet': '🏍️ Motocicletas',
  },
  ru: {
    '🎵 Müzik': '🎵 Музыка', '🎧 Elektronik Müzik': '🎧 Электронная Музыка', '🎛️ Techno': '🎛️ Техно',
    '🪩 Rave / Club': '🪩 Рейв / Клуб', '🎤 Konser': '🎤 Концерты', '🎸 Rock': '🎸 Рок',
    '🎹 Indie': '🎹 Инди', '🎙️ Hip-Hop': '🎙️ Хип-Хоп', '🎶 Pop': '🎶 Поп', '🎷 Jazz': '🎷 Джаз',
    '🎼 Klasik': '🎼 Классика', '🕺 Gece Hayatı': '🕺 Ночная Жизнь', '🍸 Kokteyl Mekanları': '🍸 Коктейль-Бары',
    '🎉 Festival': '🎉 Фестивали',
    '🎬 Sinema': '🎬 Кино', '📺 Diziler': '📺 Сериалы', '🎭 Tiyatro': '🎭 Театр', '🎨 Sanat': '🎨 Искусство',
    '🏛️ Müze': '🏛️ Музеи', '📚 Kitap': '📚 Книги', '✍️ Yazarlık': '✍️ Писательство', '📖 Şiir': '📖 Поэзия',
    '🎞️ Bağımsız Filmler': '🎞️ Независимое Кино', '😂 Komedi': '😂 Комедия', '🎌 Anime': '🎌 Аниме',
    '✈️ Seyahat': '✈️ Путешествия', '🏕️ Kamp': '🏕️ Кемпинг', '🥾 Hiking': '🥾 Пешие Походы', '🏖️ Sahil': '🏖️ Пляж',
    '🌿 Doğa': '🌿 Природа', '🚗 Road Trip': '🚗 Автопутешествия', '🏔️ Dağlar': '🏔️ Горы',
    '🌍 Yeni Kültürler': '🌍 Новые Культуры', '🧳 Weekend Getaway': '🧳 Поездки на Выходные', '🌅 Gün Batımı': '🌅 Закаты',
    '☕ Kahve': '☕ Кофе', '🍕 Pizza': '🍕 Пицца', '🍣 Sushi': '🍣 Суши', '🍝 İtalyan Mutfağı': '🍝 Итальянская Кухня',
    '🌮 Sokak Lezzetleri': '🌮 Стритфуд', '🍳 Brunch': '🍳 Бранч', '🍰 Tatlı': '🍰 Десерты',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 Готовка', '🍵 Çay': '🍵 Чай', '🥗 Sağlıklı Beslenme': '🥗 Здоровое Питание',
    '🏋️ Fitness': '🏋️ Фитнес', '🏃 Koşu': '🏃 Бег', '⚽ Futbol': '⚽ Футбол', '🏀 Basketbol': '🏀 Баскетбол',
    '🎾 Tenis': '🎾 Теннис', '🏊 Yüzme': '🏊 Плавание', '🚴 Bisiklet': '🚴 Велоспорт', '🧘 Yoga': '🧘 Йога',
    '🥊 Boks': '🥊 Бокс', '🏄 Su Sporları': '🏄 Водные Виды Спорта', '🎿 Kayak': '🎿 Лыжи', '💪 Gym': '💪 Спортзал',
    '📷 Fotoğrafçılık': '📷 Фотография', '🎥 Video': '🎥 Видео', '🎨 Tasarım': '🎨 Дизайн',
    '💻 Teknoloji': '💻 Технологии', '🤖 Yapay Zeka': '🤖 Искусственный Интеллект', '🎮 Oyun': '🎮 Игры',
    '🕹️ Retro Oyun': '🕹️ Ретро-Игры', '🎧 Podcast': '🎧 Подкасты', '🎹 Müzik Üretimi': '🎹 Создание Музыки',
    '🧑‍💻 Kodlama': '🧑‍💻 Программирование',
    '🐾 Evcil Hayvanlar': '🐾 Домашние Животные', '🐶 Köpekler': '🐶 Собаки', '🐱 Kediler': '🐱 Кошки',
    '💃 Dans': '💃 Танцы', '🪩 Clubbing': '🪩 Клубы', '🎉 Partiler': '🎉 Вечеринки',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 Встречи с Друзьями',
    '🧠 Kişisel Gelişim': '🧠 Личностный Рост', '♟️ Masa Oyunları': '♟️ Настольные Игры', '🎲 Board Games': '🎲 Board Games',
    '🚘 Arabalar': '🚘 Автомобили', '🏍️ Motosiklet': '🏍️ Мотоциклы',
  },
  ar: {
    '🎵 Müzik': '🎵 موسيقى', '🎧 Elektronik Müzik': '🎧 موسيقى إلكترونية', '🎛️ Techno': '🎛️ تكنو',
    '🪩 Rave / Club': '🪩 رايف / نادي', '🎤 Konser': '🎤 حفلات', '🎸 Rock': '🎸 روك',
    '🎹 Indie': '🎹 إندي', '🎙️ Hip-Hop': '🎙️ هيب هوب', '🎶 Pop': '🎶 بوب', '🎷 Jazz': '🎷 جاز',
    '🎼 Klasik': '🎼 كلاسيكية', '🕺 Gece Hayatı': '🕺 الحياة الليلية', '🍸 Kokteyl Mekanları': '🍸 بارات الكوكتيل',
    '🎉 Festival': '🎉 مهرجانات',
    '🎬 Sinema': '🎬 سينما', '📺 Diziler': '📺 مسلسلات', '🎭 Tiyatro': '🎭 مسرح', '🎨 Sanat': '🎨 فن',
    '🏛️ Müze': '🏛️ متاحف', '📚 Kitap': '📚 كتب', '✍️ Yazarlık': '✍️ الكتابة', '📖 Şiir': '📖 شعر',
    '🎞️ Bağımsız Filmler': '🎞️ أفلام مستقلة', '😂 Komedi': '😂 كوميديا', '🎌 Anime': '🎌 أنمي',
    '✈️ Seyahat': '✈️ سفر', '🏕️ Kamp': '🏕️ تخييم', '🥾 Hiking': '🥾 المشي لمسافات طويلة', '🏖️ Sahil': '🏖️ شاطئ',
    '🌿 Doğa': '🌿 طبيعة', '🚗 Road Trip': '🚗 رحلة بالسيارة', '🏔️ Dağlar': '🏔️ جبال',
    '🌍 Yeni Kültürler': '🌍 ثقافات جديدة', '🧳 Weekend Getaway': '🧳 رحلة نهاية الأسبوع', '🌅 Gün Batımı': '🌅 غروب الشمس',
    '☕ Kahve': '☕ قهوة', '🍕 Pizza': '🍕 بيتزا', '🍣 Sushi': '🍣 سوشي', '🍝 İtalyan Mutfağı': '🍝 المطبخ الإيطالي',
    '🌮 Sokak Lezzetleri': '🌮 أطعمة الشارع', '🍳 Brunch': '🍳 برانش', '🍰 Tatlı': '🍰 حلويات',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 الطبخ', '🍵 Çay': '🍵 شاي', '🥗 Sağlıklı Beslenme': '🥗 التغذية الصحية',
    '🏋️ Fitness': '🏋️ لياقة بدنية', '🏃 Koşu': '🏃 الجري', '⚽ Futbol': '⚽ كرة القدم', '🏀 Basketbol': '🏀 كرة السلة',
    '🎾 Tenis': '🎾 التنس', '🏊 Yüzme': '🏊 السباحة', '🚴 Bisiklet': '🚴 ركوب الدراجات', '🧘 Yoga': '🧘 يوغا',
    '🥊 Boks': '🥊 الملاكمة', '🏄 Su Sporları': '🏄 الرياضات المائية', '🎿 Kayak': '🎿 التزلج', '💪 Gym': '💪 الجيم',
    '📷 Fotoğrafçılık': '📷 التصوير الفوتوغرافي', '🎥 Video': '🎥 فيديو', '🎨 Tasarım': '🎨 تصميم',
    '💻 Teknoloji': '💻 تقنية', '🤖 Yapay Zeka': '🤖 الذكاء الاصطناعي', '🎮 Oyun': '🎮 ألعاب',
    '🕹️ Retro Oyun': '🕹️ ألعاب كلاسيكية', '🎧 Podcast': '🎧 بودكاست', '🎹 Müzik Üretimi': '🎹 إنتاج الموسيقى',
    '🧑‍💻 Kodlama': '🧑‍💻 البرمجة',
    '🐾 Evcil Hayvanlar': '🐾 حيوانات أليفة', '🐶 Köpekler': '🐶 كلاب', '🐱 Kediler': '🐱 قطط',
    '💃 Dans': '💃 رقص', '🪩 Clubbing': '🪩 النوادي الليلية', '🎉 Partiler': '🎉 حفلات',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 قضاء الوقت مع الأصدقاء',
    '🧠 Kişisel Gelişim': '🧠 التطوير الذاتي', '♟️ Masa Oyunları': '♟️ ألعاب الطاولة', '🎲 Board Games': '🎲 ألعاب اللوح',
    '🚘 Arabalar': '🚘 سيارات', '🏍️ Motosiklet': '🏍️ دراجات نارية',
  },
  hi: {
    '🎵 Müzik': '🎵 संगीत', '🎧 Elektronik Müzik': '🎧 इलेक्ट्रॉनिक संगीत', '🎛️ Techno': '🎛️ टेक्नो',
    '🪩 Rave / Club': '🪩 रेव / क्लब', '🎤 Konser': '🎤 कॉन्सर्ट', '🎸 Rock': '🎸 रॉक',
    '🎹 Indie': '🎹 इंडी', '🎙️ Hip-Hop': '🎙️ हिप-हॉप', '🎶 Pop': '🎶 पॉप', '🎷 Jazz': '🎷 जैज़',
    '🎼 Klasik': '🎼 शास्त्रीय', '🕺 Gece Hayatı': '🕺 नाइटलाइफ़', '🍸 Kokteyl Mekanları': '🍸 कॉकटेल बार',
    '🎉 Festival': '🎉 फेस्टिवल',
    '🎬 Sinema': '🎬 सिनेमा', '📺 Diziler': '📺 टीवी शो', '🎭 Tiyatro': '🎭 थिएटर', '🎨 Sanat': '🎨 कला',
    '🏛️ Müze': '🏛️ संग्रहालय', '📚 Kitap': '📚 किताबें', '✍️ Yazarlık': '✍️ लेखन', '📖 Şiir': '📖 कविता',
    '🎞️ Bağımsız Filmler': '🎞️ इंडी फ़िल्में', '😂 Komedi': '😂 कॉमेडी', '🎌 Anime': '🎌 एनीमे',
    '✈️ Seyahat': '✈️ यात्रा', '🏕️ Kamp': '🏕️ कैम्पिंग', '🥾 Hiking': '🥾 हाइकिंग', '🏖️ Sahil': '🏖️ समुद्र तट',
    '🌿 Doğa': '🌿 प्रकृति', '🚗 Road Trip': '🚗 रोड ट्रिप', '🏔️ Dağlar': '🏔️ पहाड़',
    '🌍 Yeni Kültürler': '🌍 नई संस्कृतियाँ', '🧳 Weekend Getaway': '🧳 वीकेंड गेटअवे', '🌅 Gün Batımı': '🌅 सूर्यास्त',
    '☕ Kahve': '☕ कॉफ़ी', '🍕 Pizza': '🍕 पिज़्ज़ा', '🍣 Sushi': '🍣 सुशी', '🍝 İtalyan Mutfağı': '🍝 इतालवी भोजन',
    '🌮 Sokak Lezzetleri': '🌮 स्ट्रीट फूड', '🍳 Brunch': '🍳 ब्रंच', '🍰 Tatlı': '🍰 मिठाई',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 खाना बनाना', '🍵 Çay': '🍵 चाय', '🥗 Sağlıklı Beslenme': '🥗 स्वस्थ भोजन',
    '🏋️ Fitness': '🏋️ फिटनेस', '🏃 Koşu': '🏃 दौड़ना', '⚽ Futbol': '⚽ फुटबॉल', '🏀 Basketbol': '🏀 बास्केटबॉल',
    '🎾 Tenis': '🎾 टेनिस', '🏊 Yüzme': '🏊 तैराकी', '🚴 Bisiklet': '🚴 साइकिलिंग', '🧘 Yoga': '🧘 योग',
    '🥊 Boks': '🥊 बॉक्सिंग', '🏄 Su Sporları': '🏄 जल क्रीड़ा', '🎿 Kayak': '🎿 स्कीइंग', '💪 Gym': '💪 जिम',
    '📷 Fotoğrafçılık': '📷 फोटोग्राफी', '🎥 Video': '🎥 वीडियो', '🎨 Tasarım': '🎨 डिज़ाइन',
    '💻 Teknoloji': '💻 तकनीक', '🤖 Yapay Zeka': '🤖 आर्टिफिशियल इंटेलिजेंस', '🎮 Oyun': '🎮 गेमिंग',
    '🕹️ Retro Oyun': '🕹️ रेट्रो गेमिंग', '🎧 Podcast': '🎧 पॉडकास्ट', '🎹 Müzik Üretimi': '🎹 म्यूज़िक प्रोडक्शन',
    '🧑‍💻 Kodlama': '🧑‍💻 कोडिंग',
    '🐾 Evcil Hayvanlar': '🐾 पालतू जानवर', '🐶 Köpekler': '🐶 कुत्ते', '🐱 Kediler': '🐱 बिल्लियाँ',
    '💃 Dans': '💃 नृत्य', '🪩 Clubbing': '🪩 क्लबिंग', '🎉 Partiler': '🎉 पार्टियाँ',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 दोस्तों के साथ समय बिताना',
    '🧠 Kişisel Gelişim': '🧠 व्यक्तिगत विकास', '♟️ Masa Oyunları': '♟️ टेबल गेम्स', '🎲 Board Games': '🎲 बोर्ड गेम्स',
    '🚘 Arabalar': '🚘 कारें', '🏍️ Motosiklet': '🏍️ मोटरसाइकिल',
  },
  zh: {
    '🎵 Müzik': '🎵 音乐', '🎧 Elektronik Müzik': '🎧 电子音乐', '🎛️ Techno': '🎛️ 科技舞曲',
    '🪩 Rave / Club': '🪩 锐舞 / 夜店', '🎤 Konser': '🎤 演唱会', '🎸 Rock': '🎸 摇滚',
    '🎹 Indie': '🎹 独立音乐', '🎙️ Hip-Hop': '🎙️ 嘻哈', '🎶 Pop': '🎶 流行', '🎷 Jazz': '🎷 爵士',
    '🎼 Klasik': '🎼 古典', '🕺 Gece Hayatı': '🕺 夜生活', '🍸 Kokteyl Mekanları': '🍸 鸡尾酒吧',
    '🎉 Festival': '🎉 音乐节',
    '🎬 Sinema': '🎬 电影', '📺 Diziler': '📺 电视剧', '🎭 Tiyatro': '🎭 戏剧', '🎨 Sanat': '🎨 艺术',
    '🏛️ Müze': '🏛️ 博物馆', '📚 Kitap': '📚 书籍', '✍️ Yazarlık': '✍️ 写作', '📖 Şiir': '📖 诗歌',
    '🎞️ Bağımsız Filmler': '🎞️ 独立电影', '😂 Komedi': '😂 喜剧', '🎌 Anime': '🎌 动漫',
    '✈️ Seyahat': '✈️ 旅行', '🏕️ Kamp': '🏕️ 露营', '🥾 Hiking': '🥾 徒步', '🏖️ Sahil': '🏖️ 海滩',
    '🌿 Doğa': '🌿 自然', '🚗 Road Trip': '🚗 自驾游', '🏔️ Dağlar': '🏔️ 山脉',
    '🌍 Yeni Kültürler': '🌍 探索新文化', '🧳 Weekend Getaway': '🧳 周末小旅行', '🌅 Gün Batımı': '🌅 日落',
    '☕ Kahve': '☕ 咖啡', '🍕 Pizza': '🍕 披萨', '🍣 Sushi': '🍣 寿司', '🍝 İtalyan Mutfağı': '🍝 意大利菜',
    '🌮 Sokak Lezzetleri': '🌮 街头小吃', '🍳 Brunch': '🍳 早午餐', '🍰 Tatlı': '🍰 甜点',
    '🧑‍🍳 Yemek Yapmak': '🧑‍🍳 烹饪', '🍵 Çay': '🍵 茶', '🥗 Sağlıklı Beslenme': '🥗 健康饮食',
    '🏋️ Fitness': '🏋️ 健身', '🏃 Koşu': '🏃 跑步', '⚽ Futbol': '⚽ 足球', '🏀 Basketbol': '🏀 篮球',
    '🎾 Tenis': '🎾 网球', '🏊 Yüzme': '🏊 游泳', '🚴 Bisiklet': '🚴 骑行', '🧘 Yoga': '🧘 瑜伽',
    '🥊 Boks': '🥊 拳击', '🏄 Su Sporları': '🏄 水上运动', '🎿 Kayak': '🎿 滑雪', '💪 Gym': '💪 健身房',
    '📷 Fotoğrafçılık': '📷 摄影', '🎥 Video': '🎥 视频', '🎨 Tasarım': '🎨 设计',
    '💻 Teknoloji': '💻 科技', '🤖 Yapay Zeka': '🤖 人工智能', '🎮 Oyun': '🎮 游戏',
    '🕹️ Retro Oyun': '🕹️ 复古游戏', '🎧 Podcast': '🎧 播客', '🎹 Müzik Üretimi': '🎹 音乐制作',
    '🧑‍💻 Kodlama': '🧑‍💻 编程',
    '🐾 Evcil Hayvanlar': '🐾 宠物', '🐶 Köpekler': '🐶 狗狗', '🐱 Kediler': '🐱 猫咪',
    '💃 Dans': '💃 跳舞', '🪩 Clubbing': '🪩 夜店', '🎉 Partiler': '🎉 派对',
    '🧑‍🤝‍🧑 Arkadaşlarla Takılmak': '🧑‍🤝‍🧑 和朋友出去玩',
    '🧠 Kişisel Gelişim': '🧠 自我提升', '♟️ Masa Oyunları': '♟️ 桌面游戏', '🎲 Board Games': '🎲 桌游',
    '🚘 Arabalar': '🚘 汽车', '🏍️ Motosiklet': '🏍️ 摩托车',
  },
};

export const getLocalizedCategoryTitle = (id: string, locale?: AppLocale): string =>
  localeLookup(INTEREST_CATEGORY_TITLES_BY_LOCALE, locale, id) || id;

export const getLocalizedInterestLabel = (rawInterest: string, locale?: AppLocale): string =>
  localeLookup(INTEREST_LABELS_BY_LOCALE, locale, rawInterest) || rawInterest;
