import React, { useEffect, useRef, useState } from 'react';
import { MapPin, Mic, Square, Trash2 } from 'lucide-react';
import { apiClient } from '../services/api/apiClient';
import { mediaService, normalizeMediaUrl } from '../services/media/mediaService';
import { searchCities, type GeoCityResult } from '../services/geo/cityService';
import { toast } from '../stores/useToastStore';
import { useAppTranslation } from '../i18n/appLocale';

type Prompt = { promptCode: string; answer: string };
export const ProfileCreativeEditor: React.FC<{ city: string; onCityChange: (city: string, cityId?: number) => void; initialPrompts?: any[]; initialVoice?: any }> = ({ city, onCityChange, initialPrompts, initialVoice }) => {
  const { t } = useAppTranslation(); const c = { city:t('profileCityLabel'), prompts:t('profilePromptsLabel'), voice:t('profileVoiceIntroLabel'), add:t('profileAddPromptLabel'), record:t('profileRecordLabel'), stop:t('profileStopLabel'), save:t('saveButtonShortLabel'), remove:t('removeButtonLabel') };
  const [cityQuery,setCityQuery]=useState(city); const [cities,setCities]=useState<GeoCityResult[]>([]); const [cityChosen,setCityChosen]=useState(true);
  const [catalog,setCatalog]=useState<any>({textPrompts:[],voicePrompts:[]});
  const [prompts,setPrompts]=useState<Prompt[]>(()=>(initialPrompts||[]).map(p=>({promptCode:p.promptCode||p.code,answer:p.answer||''})).slice(0,3));
  const [voice,setVoice]=useState<any>(initialVoice||null); const [recording,setRecording]=useState(false); const [elapsed,setElapsed]=useState(0);
  const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]); const timer=useRef<ReturnType<typeof setInterval>|null>(null);
  const recordingStartedAt = useRef(0);
  useEffect(()=>{apiClient.get('/api/prompts/catalog').then(r=>setCatalog(r.data||{})).catch(e=>console.warn('[PROFILE] prompt catalog failed',e));},[]);
  useEffect(()=>{if(cityChosen||cityQuery.trim().length<2){setCities([]);return;} const h=setTimeout(()=>searchCities(cityQuery).then(setCities).catch(e=>console.warn('[PROFILE] city search failed',e)),250);return()=>clearTimeout(h);},[cityQuery,cityChosen]);
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);recorder.current?.stream.getTracks().forEach(t=>t.stop());},[]);
  const chooseCity=(item:GeoCityResult)=>{const canonical=[item.city,item.country].filter(Boolean).join(', ');setCityQuery(canonical);onCityChange(canonical,typeof item.id==='number'?item.id:Number(item.id)||undefined);setCityChosen(true);setCities([]);};
  const savePrompts=async()=>{if(prompts.some(p=>!p.answer.trim())||new Set(prompts.map(p=>p.promptCode)).size!==prompts.length)return;await apiClient.put('/api/user/prompts',{prompts});toast.success(c.save);};
  const startRecording=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const mr=new MediaRecorder(stream,{mimeType:mime});chunks.current=[];setElapsed(0);recordingStartedAt.current=Date.now();mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};mr.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);setRecording(false);const seconds=Math.min(30,Math.round((Date.now()-recordingStartedAt.current)/1000));const blob=new Blob(chunks.current,{type:mime});if(seconds<3)return;try{const upload=await mediaService.uploadMedia(blob,'voice');const audioUrl=upload.data.url;const promptCode=catalog.voicePrompts?.[0]?.code;await apiClient.post('/api/user/voice-prompt',{promptCode,audioUrl,durationSeconds:seconds});setVoice({url:audioUrl,promptCode,durationSeconds:seconds});}catch(e){console.warn('[PROFILE] voice intro save failed',e);}};recorder.current=mr;mr.start();setRecording(true);timer.current=setInterval(()=>setElapsed(v=>{if(v>=29){mr.stop();return 30;}return v+1;}),1000);}catch(e){console.warn('[PROFILE] microphone permission/recording failed',e);}};
  const deleteVoice=async()=>{await apiClient.delete('/api/user/voice-prompt');setVoice(null);};
  return <div className="space-y-6">
    <div className="space-y-2"><label className="text-micro font-extrabold text-app-muted uppercase">{c.city}</label><div className="relative"><MapPin className="absolute start-3 top-3 h-4 w-4 text-app-muted"/><input value={cityQuery} onChange={e=>{setCityQuery(e.target.value);setCityChosen(false)}} className="w-full rounded-2xl border border-app bg-input-app py-2.5 ps-10 pe-3"/>{cities.length>0&&<div className="absolute z-20 mt-1 w-full rounded-xl border border-app bg-surface shadow-elevated">{cities.slice(0,6).map(x=><button type="button" key={`${x.id}-${x.city}`} onClick={()=>chooseCity(x)} className="block w-full px-3 py-2 text-start">{x.city}{x.country?`, ${x.country}`:''}</button>)}</div>}</div></div>
    <div className="space-y-2"><label className="text-micro font-extrabold text-app-muted uppercase">{c.prompts}</label>{prompts.map((p,i)=><div key={i} className="space-y-1"><select value={p.promptCode} onChange={e=>setPrompts(v=>v.map((x,j)=>j===i?{...x,promptCode:e.target.value}:x))} className="w-full rounded-xl border border-app bg-input-app p-2">{catalog.textPrompts?.map((x:any)=><option key={x.code} value={x.code}>{x.title}</option>)}</select><div className="flex gap-2"><textarea maxLength={200} value={p.answer} onChange={e=>setPrompts(v=>v.map((x,j)=>j===i?{...x,answer:e.target.value}:x))} className="min-h-16 flex-1 rounded-xl border border-app bg-input-app p-2"/><button type="button" onClick={()=>setPrompts(v=>v.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div></div>)}<div className="flex gap-2"><button type="button" disabled={prompts.length>=3||!catalog.textPrompts?.length} onClick={()=>{const next=catalog.textPrompts.find((x:any)=>!prompts.some(p=>p.promptCode===x.code));if(next)setPrompts(v=>[...v,{promptCode:next.code,answer:''}])}} className="rounded-xl border border-app px-3 py-2">{c.add}</button><button type="button" onClick={()=>void savePrompts()} className="rounded-xl bg-brand-gradient px-3 py-2 font-bold text-white">{c.save}</button></div></div>
    <div className="space-y-2"><label className="text-micro font-extrabold text-app-muted uppercase">{c.voice}</label>{voice?.url&&<audio controls src={normalizeMediaUrl(voice.url)} className="w-full"/>}<div className="flex gap-2"><button type="button" onClick={()=>recording?recorder.current?.stop():void startRecording()} className="flex items-center gap-2 rounded-xl border border-app px-3 py-2">{recording?<Square className="h-4 w-4"/>:<Mic className="h-4 w-4"/>}{recording?`${c.stop} ${elapsed}s`:c.record}</button>{voice&&<button type="button" onClick={()=>void deleteVoice()} className="rounded-xl border border-red-500/40 px-3 py-2 text-red-500">{c.remove}</button>}</div></div>
  </div>;
};
